export const topicDtls = [
    { CSE1002: "Discrete Mathematics" },
    { MTH1101: "Calculus A" },
    { CSE1001: "Introduction to Computer Programming" },
    { PHY1001: "University Physics : Mechanics" },
    { HSS1010: "Communication and Critical Thinking" },
    { CSE2001: "Data Structure and Algorithm" },
    { CSE1004: "Introductory Graph Theory" },
    { MTH2101: "Calculus B" },
    { PHY2001: "University Physics: Electricity and Magnetism" },
    { HSS1021: "Principle of Microeconomics" },
    { CSE2141: "Computer Science Workshop1 " },
    { EET1211: "Digital Logic Design" },
    { CSE3131: "Algorithm Design 1" },
    { MTH2002: "Probability and Statistics" },
    { HSS2021: "Principle of Macroeconomics" },
    { CSE3141: "Computer Science Workshop 2" },
    { EET2211: "Computer Organisation and Architecture" },
    { CSE4131: "Algorithm Design 2" },
    { MTH3003: "Applied Linear Algebra" },
    { GEN1972: "Universal Human Values" },
    { CSE3541: "Operating Systems Workshop" },
    { CSE4049: "Design of Operating System" },
    { CSE3034: "Computer Networking" },
    { CSE3142: "Programming in Python" },
    { CSE3731: "Introduction to the Theory of Computation" },
    { CSE2733: "Intermediate Discrete Mathematics" },
    { CSE4541: "Computer Networking Workshop" },
    { CSE3151: "Introduction to Databases" },
    { CSE3035: "Cryptography and Network Security" },
    { CSE3054: "Introduction to Data Science using Python" },
    { CSE4732: "Study and Design of Compilers" },
    { CSE3734: "Introduction to Blockchain" },
    { CSE4110: "Internet of Things Projects using Python" },
    { HSS3011: "Topics in Environmental Studies" },
    { CSE4101: "Senior Design Project" },
    { CSE4947: "Web Technology Workshop 1" },
    { CSE3942: "Problem Solving and Problem Design using C" },
    { CSE4948: "Web Technology Workshop 2" },
    { CSE4937: "Web Application Development" },
    { CSE4103: "Web Development Project" },
    { CVL1013: "Civil Engineering Workshop Practice" },
    { CVL1114: "Computer Aided Drawing for Civil Engineering" },
    { CVL1011: "Engineering Mechanics" },
    { CVL2013: "Materials. Materials Testing and Evaluation" },
    { MTH3004: "Differential Equations" },
    { CVL2211: "Introductory Solid Mechanics" },
    { CVL1209: "Surveying and Geomatics Engineering" },
    { CVL3011: "Structural Analysis" },
    { CVL3171: "Transportation Engineering Design" },
    { CVL3231: "Introduction to Geotechnical Engineering" },
    { MEL3211: "Fluid Mechanics" },
    { CVL3241: "Water Resource Engineering" },
    { CVL4121: "Reinforced COncrete Design" },
    { CVL4232: "Foundation Engineering" },
    { CVL3162: "Construction Management Fundamentals" },
    { CVL3054: "Principle of Environmental Engineering" },
    { CVL4123: "Steel Structures Design Project" },
    { CVL4101: "Senior Design Project" },
    { MEL1104: "Engineering Drawing and Workshop Practice" },
    { MEL1105: "Computer Aided Drawing and Manufacturing" },
    { MTH2002: "Probability and Statistics" },
    { MTH3004: "Differential Equations" },
    { MTH3003: "Applied Linear Algebra" },
    { MEL2011: "Introductory Thermodynamics" },
    { MEL1012: "Engineering Mechanics: Statistics and Dynamics" },
    { GEN1972: "Universal Human Values" },
    { MTH4002: "Numerical Methods" },
    { MEL4013: "Applied Thermodynamics" },
    { MEL2021: "Introductory Solid Mechanics" },
    { MEL4022: "Complex Variables and Vibration Theory" },
    { MEL3031: "Design and Dynamics 1" },
    { MEL4026: "Advanced Solid Mechancis" },
    { MEL3211: "Fluid Mechanics" },
    { MEL3043: "Mechanical Engineering Materials" },
    { EET1100: "Electrical and Electronics Workshop" },
    { EET4109: "Embeeded Systems Project using Ardunio" },
    { MEL3212: "Heat Transfer" },
    { MEL3032: "Design and Dynamics 2" },
    { MEL3101: "Integrated Design and Manufacturing Project" },
    { MLE4038: "Operations Research and Production Engineering" },
    { HSS3011: "Topics in Environmental Studies" },
    { HSS2021: "Principle of Macroeconomics" },
    { EET1102: "Introduction to Electrical and Electronic Circuits" },
    { PHY3009: "University Physics :Semiconductor Physics" },
    { EET2131: "Microelectronic Devices and Circuits" },
    { EET2111: "Circuit Theory" },
    { MTH4001: "Complex Analysis" },
    { EET2051: "Signals and Systems" },
    { EET3131: "Design with Analog Integrated Circuits" },
    { EET3041: "Electromagnetic Waves I" },
    { EET3061: "Communication Systems I" },
    { EET3051: "Digital Signal Processing" },
    { EET3062: "Communication Systems II" },
    { EET4110: "Internet of Things Project using Raspberry Pi" },
    { EET4564: "Elements of Information Theory" },
    { EET4101: "Senior Design Project" },
    { EET3081: "Electrical Machines 1" },
    { EET3001: "Electrical and Electronic Measurments" },
    { EET3043: "Electromagnetic Field Theory" },
    { EET3082: "Electrical Machines 2" },
    { EET3083: "Power System Analysis and Design 1" },
    { EET3113: "Power Electronics, Devices and Circuits" },
    { EET4089: "Power System Protection: Analysis and Design " },
    { EET3084: "Power System Analysis and Design 2" },
    { EET4101: "Senior Design Project" },
];

